/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicQuizSubmitRouteImport } from './routes/api/public/quiz-submit'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQuizSubmitRoute = ApiPublicQuizSubmitRouteImport.update({
  id: '/api/public/quiz-submit',
  path: '/api/public/quiz-submit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quiz': typeof QuizRoute
  '/termos': typeof TermosRoute
  '/api/public/quiz-submit': typeof ApiPublicQuizSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quiz': typeof QuizRoute
  '/termos': typeof TermosRoute
  '/api/public/quiz-submit': typeof ApiPublicQuizSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quiz': typeof QuizRoute
  '/termos': typeof TermosRoute
  '/api/public/quiz-submit': typeof ApiPublicQuizSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/politica-de-privacidade'
    | '/quiz'
    | '/termos'
    | '/api/public/quiz-submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/politica-de-privacidade'
    | '/quiz'
    | '/termos'
    | '/api/public/quiz-submit'
  id:
    | '__root__'
    | '/'
    | '/cookies'
    | '/politica-de-privacidade'
    | '/quiz'
    | '/termos'
    | '/api/public/quiz-submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  QuizRoute: typeof QuizRoute
  TermosRoute: typeof TermosRoute
  ApiPublicQuizSubmitRoute: typeof ApiPublicQuizSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/quiz-submit': {
      id: '/api/public/quiz-submit'
      path: '/api/public/quiz-submit'
      fullPath: '/api/public/quiz-submit'
      preLoaderRoute: typeof ApiPublicQuizSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  QuizRoute: QuizRoute,
  TermosRoute: TermosRoute,
  ApiPublicQuizSubmitRoute: ApiPublicQuizSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
